.TH TDPROBE 1 ??? "jtdutils 0.6"
.SH NAME
tdprobe - a tool for automagically analyzing thread dumps
.SH SYNOPSIS
.B tdprobe
.RI [OPTION]
.RI [FILE]
.SH DESCRIPTION
tdprobe is currently just experimental. It's goal is to be some kind of 
neural network which automatically analyzes thread dumps based on historic
data and configuration.
.br
If FILE is given it has to point to a plain text file containing thread dumps. All text that cannot be recognized to be part of a thread dump will be ignored.
.br
Instead of providing a FILE you may also pipe the text to tdprobe.
.SH OPTIONS
.SS General programm options
.TP 10
-h, --help
Print the very small help.
.TP
-v, --version
Print version information.
.SH SEE ALSO
tdstrip, tdgrep, tdfilter
.SH AUTHOR
Stefan Lotties, <slotties@gmail.com>
