.TH TDLOCKS 1 ??? "jtdutils 0.6"
.SH NAME
tdlocks - display all java locks in dumps having the tdstrip-format
.SH SYNOPSIS
.B tdlocks
.RI [[-c\ CLASS]\ [-w\ NUMBER]\ |\ -h\ |\ -v]
.RI [FILE]
.SH DESCRIPTION
tdlocks reads Java thread dumps in the JVM independent format of tdstrip and displays lists of locks both with the owner and waiting threads.
.br
If FILE is given it has to point to a plain text file containing thread dumps. All text that cannot be recognized to be part of a thread dump will be ignored.
.br
FILE may be omitted when redirecting the the text via standard input to this tool.
.SH OPTIONS
.SS General programm options
.TP 10
-h, --help
Print the very small help.
.TP
-v, --version
Print version information.
.SS Filtering options
.TP 10
-c CLASS, --lock-class CLASS
Just display locks on objects of CLASS.
.TP
-w NUMBER, --minimum-waiting NUMBER
Just display locks having at least NUMBER threads waiting for it.
.SH SEE ALSO
tdstrip, tdgrep, tdfilter, tdlocks, tdstat, tdls
.SH AUTHOR
Stefan Lotties, <slotties@gmail.com>
