.TH TDPAGER 1 ??? "jtdutils 0.6"
.SH NAME
tdpager - a tool for browsing in thread dumps
.SH SYNOPSIS
.B tdpager
.RI [OPTION]
.RI [FILE]
.SH DESCRIPTION
tdpager provides browsing functionalities for thread dumps.
.br
If FILE is given it has to point to a plain text file containing thread dumps. All text that cannot be recognized to be part of a thread dump will be ignored.
.br
Instead of providing a FILE you may also pipe the text to tdpager.
.SH OPTIONS
.SS General programm options
.TP 10
-h, --help
Print the very small help.
.TP
-v, --version
Print version information.
.SH SEE ALSO
tdstrip, tdgrep, tdfilter, tdlocks, tdstat, tdls
.SH AUTHOR
Stefan Lotties, <slotties@gmail.com>
